<?php

declare(strict_types=1);

const STELLAR_TFM_MAIN_ACCOUNT = 'GDOJK7UAUMQX5IZERYPNBPQYQ3SHPKGLF5MBUKWLDL2UV2AY6BIS3TFM';
const STELLAR_TFM_DONATION_ACCOUNT = 'GCSAXEHZBQY65URLO6YYDOCTRLIGTNMGCQHVW2RZPFNPTEJN6VN7TFIN';
const EURMTL_ISSUER = 'GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V';
const TG_WALLET_BOT_BASE = 'https://t.me/MyMTLWalletBot?start=';
const MTL_REDIRECT_BASE = 'https://montelibero.net/redirect/?to=';
const TG_CHANNEL = 'https://t.me/tfm_voice';
const WIKI_ROOT_RU = 'https://monte.wiki/ru/';
